<?php

namespace Misa\Users\Domain\Employee;

use Misa\Common\Adapter\Persistence\Doctrine\MisaRepository;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
interface EmployeeRepository extends MisaRepository
{
    /**
     * @param $filter
     * @return array
     */
    public function listAll($filter);

    /**
     * @param Employee $employee
     * @return bool
     */
    public function persist(Employee $employee);

    /**
     * @param $user
     * @return Employee
     */
    public function findByUser($user);
}
